LOVELY_NAMES = [
    "My Wife 👰🏻‍♀",
    "My Love 🥰",
    "My Dearest 🌹",
    "My Most Beautiful 🌟",
    "My Blessed One 🌞",
    "My Sweetest 🍯",
    "Star of My World ✨",
    "My Heart ❤️",
    "My Sun ☀️",
    "My Everything 💖",
    "My Angel 👼",
    "My Soul 💫",
    "Joy of My Life 🎶",
    "My Magic 🎩",
    "Light of My Day 💡",
    "My Queen 👑",
    "My Happiness 🍀",
    "My Inspiration 🖌️",
    "My Priceless Treasure 💎",
    "My Dream I Don't Want to End 🌙",
    "My Caress 🌊",
    "The Tenderness in My Life 🕊️",
    "The Secret to My Peace 🔮",
    "The World in My Eyes 🌍",
    "My Endless Miracle 🌠",
    "My Happy Heart 🎈",
    "My Irreplaceable One 🌷",
    "My Endless Sky ☁️",
    "My Most Beautiful Artwork 🎨",
    "My Ray of Hope 🌅",
    "My Eternal Refuge 🏡",
    "The Reason for My Happiness 🎊",
    "Light in My Soul 🔥",
    "My Melody 🎶",
    "The Warmest Hug 🤗",
    "My Gentle Light 🕯️",
    "My Little Flower 🌺",
    "One and Only 🌈",
    "My Warm Miracle 🔥",
    "My Most Precious 💰",
    "The Soul I Love ❤️‍🔥",
    "My Everlasting Sun 🌞",
    "My Constant Joy 🎇",
    "My Heavenly Light 🌌",
    "My Purest Treasure 🌼",
    "My Eternal Love 💑",
    "My Beautiful Destiny 🌟",
    "The Best Part of Me ❤️"
]
